### ISSUE TITLE
Any change we'll get a version compatible with R 3.0.2 soon? 

### ISSUE THREAD

**Issue by phonixor** [chainsawriot/readODS#14]
http://stackoverflow.com/questions/21989585/how-to-import-ods-file-in-r/

Any change we'll get a version compatible with R 3.0.2 soon? I'm getting this message after running install.packages("readODS"): "package ‘readODS’ is not available (for R version 3.0.2)". –  Waldir Leoncio Nov 20 at 13:52

**Comment by chainsawriot** [comment]
Tested with 3.2.2

Reference: 9d2800a7f8df699c6b488f5bb58116e5be867f1f
