### ISSUE TITLE
Add na.string parameter

### ISSUE THREAD

**Issue by Deleetdk** [chainsawriot/readODS#17]
If the ODF file has empty cells, they are read as "" (empty strings). This is usually not what is wanted. They should be loaded as NA. This should also be the default. However, it would be wise to keep a parameter for this in case there are more than one possible string for missing values, such as often found in survey datasets.

Because this isn't there, one has to do replacing after loading, which cancels the benefits of using this loader as opposed to saving the ODS files as .csv and just using read.csv().

**Comment by phonixor** [comment]
i disagree, in excel there is no difference between "" and NA...
df[df=""]=NA
bigger problem is that the xml i use is to damn slow for some files...
