### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by Deleetdk** [chainsawriot/readODS#18]
When I open a file with non-English letters they are encoded incorrectly. There doesn't seem to be any encoding options I can change. Example file: http://emilkirkegaard.dk/en/wp-content/uploads/dutch_crime_area.ods

![readods encoding](https://cloud.githubusercontent.com/assets/6759913/10126826/3ba7106c-655e-11e5-819e-4a14c6afcd36.png)

**Comment by chainsawriot** [comment]
Fixed with the xml2 rebuilt (with default UTF-8). I have tested with the ODS file you mentioned.

Reference: 9d2800a7f8df699c6b488f5bb58116e5be867f1f
