### ISSUE TITLE
Prepare a 1.6 version for CRAN submission

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/readODS#20]
- [x] Fix as many issues as possible, or at least note it in the documentation
    - [x] #17 
    - [x] #15 Probably cannot fix this in short time, add a note in the documentation
    - [x] #13 Infer the type from value-type alas read.csv?
    - [x] #2 ditto #15 
- [x] use jennybc/cellranger
- [x] emulate the API of readxl::read_excel
    - `header` versus `col_names`
- [ ] Data import is actually damn slow, probably because of numerous rbindings of data.frame in `parse_rows`. Need to optimize that.
    - Use sqlite?

**Comment by Deleetdk** [comment]
Thanks so much for doing a lot of good work on this package. Regarding inferring value-types, I note that `read_csv()` from hadley's *readr* package does some of this. Perhaps you should use *readr* as the backbone instead of the *base-r* functions?

**Comment by jennybc** [comment]
@Deleetdk I have this same thing on my own to do list in `googlesheets`. I do some of this already but things have changed favourably in `readr` since I released `googlesheets` last July that make this even more tractable, so I also plan to revisit an implement this idea. Good suggestion.

**Comment by chainsawriot** [comment]
Using `readr::type_convert` to guess the value-types now.
Reference: 09ea3609dda9182335787d32cbfcc698a0da1c37

**Comment by chainsawriot** [comment]
Setting optimization as a goal of 1.7
