### ISSUE TITLE
Optimization with RSQLite

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/readODS#21]
Currently the `parse_rows` use an expanding data.frame (i.e. continuously rbinding) to hold values in the ods sheet.

I have create a branch that use `RSQLite` to hold values in a in-memory DB.

The benchmark is here. Original:

```
microbenchmark::microbenchmark({read_ods('./tests/testdata/datasets.ods', 4)}, times = 10)
Unit: seconds
                                                 expr      min       lq    mean
 {     read_ods("./tests/testdata/datasets.ods", 4) } 14.94037 15.01843 15.4036
  median       uq      max neval
 15.2089 15.60137 16.52064    10
```

RSQLite.

```
Unit: seconds
                                                 expr     min       lq     mean
 {     read_ods("./tests/testdata/datasets.ods", 4) } 6.48596 7.434865 8.406698
   median       uq      max neval
 8.030323 8.929039 11.75338    10
```

This small hack can reduce the parsing time. But on the other hand, we need to make this package depends on RSQLite and DBI. So I put this as a separate branch.

https://github.com/chainsawriot/readODS/tree/sqlite

**Comment by phonixor** [comment]
what i planned todo, but failed
was to first get the amount of rows and columns, and then at the start
already create the date.frame in the right size.

_______________________________________________
phonixor perfection improved
