### ISSUE TITLE
multi-line .ods files

### ISSUE THREAD

**Issue by hector1980** [chainsawriot/readODS#23]
Hi,
It seems readODS does not support multi-line .ods files (e.g. one cell with multiple lines, using Ctrl+Enter to write every line). I have checked the code and it seems pretty easy to add a workaround:

You just have to slightly modify the main for loop of the "to_data_frame" function like this:

    for(i in 1:nrow(cell_values)){
        my_row <- cell_values[i, 1]
        my_col <- cell_values[i, 2]
        previous_value = res[my_row, my_col]
        if ( previous_value == "") res[my_row, my_col] = cell_values[i, 3]
        else res[my_row, my_col] = paste(previous_value, cell_values[i, 3], sep='\n') #support for multi-line cells
    }

I hope this helps (I attach an example of .ods file with a multiline cell).
Best regards,
Hector
[multiline_cells.zip](https://github.com/chainsawriot/readODS/files/180764/multiline_cells.zip)

**Comment by MVKohnen** [comment]
Alternativly one could add inside the parse_single_cell() function a paste command to concatenate the line with \n.

E.G:
parse_single_cell <- function(cell, ods_ns, formula_as_formula = FALSE, use_office_value = TRUE) {
    cell_value <- xml_text(xml_find_all(cell, ".//text:p", ods_ns))
    cell_value <- paste0(cell_value, collapse = "\n")          #                      <------     line added
    if (cell_value == "" & use_office_value & xml_has_attr(cell, "office:value", ods_ns)) {

[...]
}

**Comment by chainsawriot** [comment]
Thanks @hector1980 and @MVKohnen for providing the fix for this.
