### ISSUE TITLE
read_ods function defaults incorrectly to parsed_df

### ISSUE THREAD

**Issue by zeillemaker** [chainsawriot/readODS#24]
Hi, 

After encountering some problems using the read_ods function - I was only able to import data from ods files as text - I have checked the code and think I have found a solution.

Within the read_ods function, after creating the parsed_df, some checks are done. The second check will always result in a true value, and will never allow the following else statement. See below.

`
if (is.na(NA)) {
        raw_sheet <- parsed_df
    } else ....
`

As stated above the code of the function, col_types can be NULL, a character vector or NA. The code below should provide the correct behaviour. Allowing the else statement to call the readr package using a character vector of col_types.

`
if (is.na(col_types)) {
        raw_sheet <- parsed_df
    } else ....
`

**Comment by chainsawriot** [comment]
Thanks for pointing out the bug! I have fixed that accordingly and provided a unit testing.
