### ISSUE TITLE
col_types not working

### ISSUE THREAD

**Issue by junoslukan** [chainsawriot/readODS#27]
The option col_types is not working if set e.g. `col_types = "numeric"`. Looking at `readr` documentation, it seems to me that [col_types should be specified](https://cran.r-project.org/web/packages/readr/vignettes/column-types.html) in a different manner.  Should `readODS` be updated to reflect this?

Test case:
**test.ods**

| first |
| --- |
| 1 |

**non-working code**

``` r
read_ods("test.ods", col_types = "numeric")
```

**Comment by chainsawriot** [comment]
It is because the new version of `readr` no longer accept character string such as 'cci' as column specification in `type_convert`.
I will update the documentation to reflect this.

**Comment by jennybc** [comment]
@chainsawriot Yeah, I'm tracking that as well and wondering what to do about it: https://github.com/hadley/readr/issues/517. googlesheets doesn't technically rely on this but my examples and tests certainly did.
