### ISSUE TITLE
Column specification message lying...

### ISSUE THREAD

**Issue by MichaelChirico** [chainsawriot/readODS#29]
Not sure if this is the same as #27, but I got the following message when reading in a file:

```
# Parsed with column specification:
# cols(
#   Name = col_character(),
#   PS1 = col_double(),
#   PS2 = col_double(),
#   PS3 = col_double(),
#   PS4 = col_double(),
#   PS5 = col_double(),
#   PS6 = col_double(),
#   PS7 = col_double(),
#   Midterm = col_double(),
#   Quiz = col_double()
# )
```

But when I do `sapply(data, class)` thereafter, all columns are `character`?

**Comment by Deleetdk** [comment]
This is the output from **readr** package. It uses other names because that's the way Hadley likes to roll.

**Comment by MichaelChirico** [comment]
Yep, that's my point... is that `readr` doing it, or `read_ods`?

**Comment by MichaelChirico** [comment]
OK, so I think I found a bug:

```
  if (is.null(col_types)) {
    raw_sheet <- readr::type_convert(df = parsed_df)
  }
  if (is.na(NA)) {
    raw_sheet <- parsed_df
  }
  else {
    raw_sheet <- readr::type_convert(df = parsed_df, col_types = col_types)
  }
```

After the `is.null(col_types)`, the `raw_sheet` that results has correctly been parsed with the right types:

```
sapply(raw_sheet, class)
#        Name         PS1         PS2         PS3         PS4         PS5 
# "character"   "numeric"   "numeric"   "numeric"   "numeric"   "numeric" 
#         PS6         PS7     Midterm        Quiz 
#   "numeric"   "numeric"   "numeric"   "numeric" 
```

However, `raw_sheet` is then overwritten because the `if` branch `if (is.na(NA))` is trivially `TRUE`.

I would give a pull request to fix this, but I don't know what the point of that branch is?

**Comment by MichaelChirico** [comment]
I have an idea. going to push now...

**Comment by MichaelChirico** [comment]
Apparently this was fixed in development.
