### ISSUE TITLE
Capable of choose decimal separator, "," or  "."

### ISSUE THREAD

**Issue by aConar** [chainsawriot/readODS#30]
Is it possible to add and argument to choose decimal separator, like in read.table?

Thanks

**Comment by chainsawriot** [comment]
I don't quite understand your requirement. Would you please provide an example ods file and the expected output? Thank you.

**Comment by zeehio** [comment]
This zipped ods file generated with LibreOffice has a comma as decimal separator. The number 3,4  is interpreted as 34 by read_ods.

[example_decimal_comma.ods.zip](https://github.com/chainsawriot/readODS/files/785773/example_decimal_comma.ods.zip)
