### ISSUE TITLE
na= parameter is vectorized (this not documented and maybe not the desired behaviour)

### ISSUE THREAD

**Issue by katossky** [chainsawriot/readODS#34]
Writing `read_ods(sheet='myfile', na=c('', '?', 'missing'))` is interpreted as:

- use ` ` for `NA` for the fist variable
- use `?` for `NA` for the second variable
- use `missing` for the third
- start over again with  ` ` for the fourth, `?` for the fifth and `missing` for the sixth variables.

This is most probably not the desired behaviour. I expected that **all** the specified values are replaced by `NA` for **all** the variables (table-wise), and I guess most people would expect the same. Recycling is, however, what one would **never** expect.

Arguably, one could say that if `na=` is a vector of the same size as the number of column, then it should be interpreted as the `NA`-string to be valid in each corresponding column. But I think it is a bad idea, since it would be a programmatic hassle: in a table with 2 columns, who can tell the difference between 1 `NA`-string by column and 2 `NA`-strings to be valid for the whole table.

I suggest that if `na=` is a vector, then it must be interpreted as valid for the whole table. And that if it is a named list, or a list with as many elements as the table has columns, then it is interpreted as to be valid column-wise. There is then no way to specify both a table-wise and a column-specific `NA` string, but eh, nothing is perfect.

I can implement the change as soon as I get (hopefully positive) feedbacks.

**Comment by chainsawriot** [comment]
Thanks a lot for the report. I agree it is not the expected behavior. The API of `read_ods` is emulating `readxl::read_excel` and its `na` parameter is:

> Character vector of strings to use for missing values. By default readxl converts blank cells to missing data.

So, it should be modified. I will patch that later.
