### ISSUE TITLE
Decimal with comma still buggy

### ISSUE THREAD

**Issue by fred777** [chainsawriot/readODS#42]
This is related to https://github.com/chainsawriot/readODS/pull/35 and https://github.com/chainsawriot/readODS/issues/30

On my machine (Archlinux 64Bit, R 3.4.1), comma will not be interpreted as decimal point properly: either it is just ignored or the related number is just imported as character, see attached [test.ods.zip](https://github.com/chainsawriot/readODS/files/1248767/test.ods.zip) which results in
```
> readODS::read_ods("/tmp/test.ods")
Parsed with column specification:
cols(
  `1,00` = col_character(),
  `0,00` = col_number(),
  `0,50` = col_character()
)
  1,00 0,00 0,50
1 0,50  100 0,75
```
Expected: 
```
1,00 0,00 0,50
0,50 1,00 0,75
```

Also, the test file https://github.com/chainsawriot/readODS/blob/master/tests/testdata/decimal_comma.ods is not imported correctly:

```
> read_ods('~/Downloads/decimal_comma.ods')
Parsed with column specification:
cols(
  A = col_number(),
  B = col_character(),
  C = col_character()
)
   A      B     C
1 34 2,30 € 3,00%
```

Maybe related to system-specific localization settings - I have LANG=en_DK.utf8 and LANGUAGE=en_DK.utf8

**Comment by chainsawriot** [comment]
I have tested your case with the latest version of readODS (1.6.7) and readr (1.1.1), it seems to work fine with either en_DK.UTF-8 and de_DE.UTF-8 locales. Please test it again with the latest version.

**Comment by fred777** [comment]
I just tested it with R 3.5.1, readODS 1.6.7, and readr 1.2.1 -> seems to be fixed.
