### ISSUE TITLE
when a column is a col_skip() type, then it should skip the column

### ISSUE THREAD

**Issue by gpoo** [chainsawriot/readODS#48]
When I specify some columns as `col_skip()`, `read_ods()` complains there are insufficient `col_types`.

For example, a spreadsheet with 14 columns, when I set 3 of them a `col_skip()` I get the following output:

```
Insufficient `col_types`. Guessing 3 columns. 
```

If I replace, `col_skip()` by something else like `col_character()`, then it does not complain. But it fails on what I am trying to accomplish.

**Comment by gpoo** [comment]
For what it is worth, I am using readODS 1.6.4 and readr 1.1.1.

Even though the error is triggered in readr, it might be something on how it is called. I have not dag in the code to check it.

**Comment by gpoo** [comment]
Here a piece of code to reproduce it:

```R
library(readODS)
library(here)

ods_file = here('test-case.ods')
ods_columns = cols(col_integer(), col_double(), col_skip())
read_ods(path=ods_file, sheet=1, col_types=ods_columns)
```

The output is the following:
```
Error in if (is.na(name)) { : argument is of length zero
In addition: Warning messages:
1: In if (is.na(col_types)) { :
  the condition has length > 1 and only the first element will be used
2: Insufficient `col_types`. Guessing 1 columns. 
3: In is.na(name) : is.na() applied to non-(list or vector) of type 'NULL'
```

and the spreadsheet ('test-case.ods') only has one sheet with the following content:

Year | Price | Note
-- | -- | --
2001 | 5000 |  
2002 | 6000 | Foo
2003 | 8000 |

**Comment by chainsawriot** [comment]
Thanks for reporting that. I have tested your case with the new version of readODS (1.6.7) and readr (1.1.1) and it doesn't throw such error anymore. Please consider updating.
