### ISSUE TITLE
read from url

### ISSUE THREAD

**Issue by alexander-newton** [chainsawriot/readODS#50]
Is there any possibility of developing this to read directly from a url as per read.csv?

At the moment it says when submitting a url as argument:

> `Error in parse_ods_file(file) : file does not exist`

I would prefer to not include any side-effects where possible in my code, so ideally would prefer to not have to download data initially.

**Comment by chainsawriot** [comment]
It can be implemented. If you need such functionality right now, you may use `rio`.
