### ISSUE TITLE
Prevent reading comments as cell data

### ISSUE THREAD

**Issue by scwatts** [chainsawriot/readODS#52]
Hello, 

Thanks for writing readODS, I've found it very helpful in my analyses! I ran into an issue where comments in my ods files were read as actual cell data and I don't think this is intended behaviour. Comments seem to be represented within the `<office:annotation />` tag under `<table:table-cell />` and along side the actual cell data:
```xml
          <table:table-cell office:value-type="string" calcext:value-type="string">
            <office:annotation office:display="true" draw:style-name="gr1" draw:text-style-name="P2" svg:width="28.99mm" svg:height="17.99mm" svg:x="208.99mm" svg:y="9mm" draw:caption-point-x="-1.5mm" draw:caption-point-y="4.59mm">
              <dc:date>2019-05-21T00:00:00</dc:date>
              <text:p text:style-name="P1">
                <text:span text:style-name="T1">Comment regarding my cell data</text:span>
              </text:p>
            </office:annotation>
            <text:p>my_cell_data_string</text:p>
          </table:table-cell>
```

Currently a call to `xml2::xml_find_all` uses an XPath query that collects all `<text:p />` tags within each cell, including those inside comments (readODS.R#L90). A fix for this would be to restrict the XPath query to only retrieve `<text:p />` tags that are direct children of each cell.

I've applied this fix over at https://github.com/scwatts/readODS/commit/aa3ea55d7f4448195de9482d4a520aa1e8bdb478 and also checked that it doesn't break multiline cell data (https://github.com/chainsawriot/readODS/issues/23). If this is something you'd like to see merged, I'd be very happy to make a pull request.
Thanks!

**Comment by stragu** [comment]
@chainsawriot , could this be merged for a future version? I often run into this issue because I use comments to my variable headers to give context and units.

**Comment by chainsawriot** [comment]
@scwatts Could you send me a pull request?

**Comment by scwatts** [comment]
Yes no problems!

**Comment by chainsawriot** [comment]
@scwatts Thanks!
@stragu now merged!
