### ISSUE TITLE
Memory error when reading medium sized file

### ISSUE THREAD

**Issue by Robinlovelace** [chainsawriot/readODS#55]
Hi @chainsawriot, thanks for a great package! It's been working well for me until I tried this:

```r
download_and_read_ods_file = function(x) {
  file_name = basename(x)
  message("Downloading file ", file_name, " from ", x)
  download.file(x, file_name)
  readODS::read.ods(file_name)
}
x = "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/748222/jts0509.ods"
download_and_read_ods_file(x)
```

As reported by @joeytalbot this also seems to fail on Windows, with the following message: 

```
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Memory allocation failed : growing input buffer [2]
```

It consumed 20+ GB RAM!

Cheers.

**Comment by chainsawriot** [comment]
Could you use `readODS::read_ods` instead?

It works on my machine.

**Comment by Robinlovelace** [comment]
Aha, yes that works, many thanks (confusing there are 2 versions, worth depreciating one?).
