### ISSUE TITLE
read_ods reading one more row than required

### ISSUE THREAD

**Issue by SantiagoCapobianco** [chainsawriot/readODS#57]
I'm using read_ods() from the readODS package for getting a table from a LibreOffice spreadsheet into r. It works but it seems to read one more row than expected:

```
        > read_ods(data_dir %+% "OpenDocument Spreadsheet.ods", sheet = "Sheet1", range = "A1:B4")
    Parsed with column specification:
    cols(
      A = col_character(),
      B = col_character()
    )
              A         B
    1         1         4
    2         2         5
    3         3         6
    4 DoNotRead DoNotRead
```
The table has 4 rows including titles, but read_ods gets 5 rows (1 titles row + 4). If I set the range argument with one less row (which is wrong) I get the expected result:

 ```
   > read_ods(data_dir %+% "OpenDocument Spreadsheet.ods", sheet = "Sheet1", range = "A1:B3")
    Parsed with column specification:
    cols(
      A = col_character(),
      B = col_character()
    )
      A B
    1 1 4
    2 2 5
    3 3 6

```
Thanks,

P.D. : sorry for any mistakes this is my first post in GitHub.

**Comment by chainsawriot** [comment]
Hello @SantiagoCapobianco Thanks for the feedback. Could you provide the ODS file for investigation?

**Comment by SantiagoCapobianco** [comment]
Hello @chainsawriot ! Yes, here it goes (zipped)
[OpenDocument Spreadsheet.zip](https://github.com/chainsawriot/readODS/files/4799198/OpenDocument.Spreadsheet.zip)
. I can also add that I'm ussing R version 3.6.3, readODS 1.6.7 in Xubuntu 18.04.4 LTS. Also `%+%` is:

`"%+%" <- function(x,y) paste(x, y, sep = "")`

Thanks!

**Comment by chainsawriot** [comment]
I can confirm this bug. 

``` r
readODS::read_ods("~/dev/readODS/OpenDocument Spreadsheet 2.ods", range = "A1:B4")
#> Parsed with column specification:
#> cols(
#>   A = col_character(),
#>   B = col_character()
#> )
#>           A         B
#> 1         1         4
#> 2         2         5
#> 3         3         6
#> 4 DoNotRead DoNotRead
readxl::read_xlsx("~/dev/readODS/OpenDocument Spreadsheet 2.xlsx", range = "A1:B4")
#> # A tibble: 3 x 2
#>       A     B
#>   <dbl> <dbl>
#> 1     1     4
#> 2     2     5
#> 3     3     6
```

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A fix is underway. Thanks for reporting this bug.

**Comment by chainsawriot** [comment]
Thanks for reporting this bug. It is now fixed.

**Comment by SantiagoCapobianco** [comment]
@chainsawriot Thanks to you and all the readODS contributors!!
