### ISSUE TITLE
write_ods: user interface for v1.7

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/readODS#61]
Thanks to the pull request from @drjxf , this package is significantly improved.

@drjxf proposes to have a separate `read_ods_2` which can update and append a new sheet to an existing ods file, which is very neat. It also makes #56 possible. However, there is no reason to split it into `read_ods` and `read_ods_2`. So, my proposal is to join them back together, so that we have only `read_ods` but it can append and update, like @drjxf 's `read_ods_2`.

@drjxf 's `read_ods_2` uses combinations of `overwrite_file` and `overwrite_sheet` to govern its behaviors. Although the manual prepared by @drjxf has a truth table describing these behaviors, it is not very intuitive.

| File exists | Sheet exists | overwrite_file | overwrite_sheet | Result |
|:----------:|:------------:|:-------------:|:----------------:|:------:|
| F | F | X | X | New file with named sheet |
| T | X | T | X | Overwrite file with named sheet |
| T | F | F | X | New sheet added to file |
| T | T | F | F | Exception thrown |
| T | T | F | T | Sheet replaced in file |

After referencing how other packages (e.g. `xlsx`) deals with this, I think parameters `append` and `update` are more intuitive.

| File exists | Sheet exists | append | update | Result |
|:----------:|:------------:|:-------------:|:----------------:|:------:|
| F | / | T or F | T or F | New file with named sheet |
| T | T or F | F | F | Overwrite the file with named sheet |
| T | F | T | T or F | New sheet appended to file |
| T | T | T | F | Error (duplicated sheet name), say there is the `update` parameter |
| T | T | T or F | T | Update content of the sheet in file |
| T | F | T or F | T | Error (No sheet) |

However, things that are intuitive to me, are not always intuitive to users. Therefore, may I ask all of you to try out

https://github.com/chainsawriot/readODS/tree/proposedv1.7

Or in R

```r
devtools::install_github("chainsawriot/readODS", ref = "proposedv1.7")
```

and give me feedback? If many of you think that this interface makes sense, then I will merge it into the master.

This message is targeted to both @drjxf and @leeper (original author of the function `write_ods`) , of course, I appreciate feedback from other users as well.

Thank you very much!

**Comment by drjxf** [comment]
Actually, its write_ods_2. While it can all be done in write_ods, I wanted to keep the functionality separate for legacy use until the changes are adopted. As for argument names, append and update are OK, but overwrite_file and overwrite_sheet are more expressive of intent.

**Comment by drjxf** [comment]
... also, when writing a sheet with row- and column-names, we get a zero at A1 - I haven't yet found the reason for this, as "" is written as the cell value!
