### ISSUE TITLE
write_ods function does not work for all ods files

### ISSUE THREAD

**Issue by bana-ne** [chainsawriot/readODS#68]
Thank you for this nice package for working with ods files. However, when trying to write a sheet to an existing file I encountered two problems and was able to fix them for my tested cases:

1. My spreadsheet was not in the indicated position: `spreadsheet <- xml2::xml_children(xml2::xml_children(content)[[3]])[[1]]`
Instead of hard coding the number I am now looking for the node office:spreadsheet.
`spreadsheet <- xml2::xml_children(xml2::xml_children(content)[[which(!is.na(xml2::xml_find_first(xml2::xml_children(content),"office:spreadsheet")))]])[[1]]`
This implementation works for my cases, but it would need some more testing, yet. 

2. In the _.find_named_sheet_ function I encountered an error, because the entries in the spreadsheet did not all contain the attribute "name" (in my case the last 2 entries were NA) and therefore the result of the if was not True/False but NA. Therefore, I changed the if statement to:
`if (!is.na(xml2::xml_attr(xml2::xml_children(ss)[[i]], "name") == name) & xml2::xml_attr(xml2::xml_children(ss)[[i]], "name") == name)`
Again, this was not tested on a large scale, but worked for me.

**Comment by chainsawriot** [comment]
Thanks for reporting this. Admittedly, `write_ods` has not been tested widely, especially for corner cases like this one.

Could you send me your ODS file? I don't think I need the data in the sheets. I only need to investigate the "sheet structure" for 1.

**Comment by bana-ne** [comment]
I have created a new file with LibreOffice Calc 6.4 and created a public [repository](https://github.com/bana-ne/write_ods_example_ods/blob/master/test_file.ods) for the file. Let me know when you have downloaded the file and I will delete the repoitory.

**Comment by chainsawriot** [comment]
@bana-ne thanks, I have downloaded the file so you can delete the repo. I am now trying to write a test to append a sheet to that file.

**Comment by chainsawriot** [comment]
@bana-ne I can confirm that is a bug and your solution seems to work fine (at least it passes all previous tests). Thank you very much. If you give me your name, I can add you as a contributor to this package.

**Comment by bana-ne** [comment]
Thank you @chainsawriot!
