### ISSUE TITLE
read.ods() : add a "header" argument

### ISSUE THREAD

**Issue by jomuller** [chainsawriot/readODS#8]
Feature request : 

It should be very usefull to be able to select a line as a header instead of the name of the column in the _.ods_. There is this option in the packages `xlsx` and `openxlsx`.

**Comment by chainsawriot** [comment]
I've wrapped read.ods to provide functionalitiy similar to header in the `rio` package.

https://github.com/leeper/rio/blob/master/R/import.R

**Comment by ofurkusi** [comment]
My preferred solution would be to follow `read.csv` and include a boolean `header` parameter with a default value of `true`.

Automatically detecting what the user wants to do can be problematic and, from the user perspective, the behaviour can sometimes be hard to understand. Allowing the user to easily choose the desired result seems to me like a simple and effective alternative.

**Comment by chainsawriot** [comment]
`header` parameter similar to that of `read.csv` has been added to the `read_ods` in the version 1.6.

reference: 9d2800a7f8df699c6b488f5bb58116e5be867f1f

**Comment by chrisdane** [comment]
Did you remove the header argument in version 1.7.0?

**Comment by chainsawriot** [comment]
`header` has been removed for a long time. The behavior of `read_ods` is now emulating `read_xls` from `readxl`. The equivalent argument is `col_names`.
