### ISSUE TITLE
row parsing error: repeated rows incorrectly treated as empty

### ISSUE THREAD

**Issue by mattkerlogue** [chainsawriot/readODS#81]
In `.parse_rows()` the attribute `table:number-rows-repeated` is assumed to indicate empty rows and thus the row is ignored and the current row counter bumped. It in fact means a set of sequential rows that are identical in value.

> The `table:number-rows-repeated` attribute specifies the number of rows to which a row element applies. If two or more rows are adjoining, and have the same content and style, and do not contain vertically merged cells, they may be described by a single `<table:table-row>` element that has a `table:number-rows-repeated` attribute with a value greater than 1.
From [ODF v1.3 schema](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#__RefHeading__1418532_253892949)

We publish a [large spreadsheet](https://www.gov.uk/government/statistics/number-of-civil-servants-by-postcode-department-responsibility-level-and-leaving-cause-2021) of 5544 rows by 11 columns. When I tried to import this into R using readODS and discovered that some 245 rows had missing values. When opening the sheet in Excel/Google Sheets these rows were rendered correctly.

Some probing around by @nacnudus identified the code in `.parse_rows()` as causing the issue. He suggests the following fix:

1. Don't check the attribute until the row has been parsed.
2. If the attribute exists, repeat the parsing of the row that number of times.

A similar issue appears with the `.check_cell_repeat()`, this again appears to be used to bump the column position for cells that have a `table:number-columns-repeated` attribute.

**Comment by chainsawriot** [comment]
@mattkerlogue @nacnudus

Thanks for reporting this. I can confirm this is a bug. I am really sorry for that.

```r
require(readODS)

res <- read_ods("Civil-servants-by-postcode-department-responsibility-level-and-leaving-cause-2021.ods", sheet = 2, skip = 4)

testthat::expect_equal(sum(is.na(res[,1])), 0)

```

I will try to provide a fix. If you like, you could also provide a pull request. That would be really great!

Thank you very much!

**Comment by mattkerlogue** [comment]
Thanks @chainsawriot, no worries. I've actually started on a fix and am testing it with the rather horrid spreadsheet that alerted me to the bug.
